### PR TITLE
Handle symlinks in zip output filenames

### PR DESCRIPTION
**Pull request by sundbry**
Fix issue #128 
This fixes the root cause for this problem https://github.com/phonegap/phonegap-app-developer/issues/299 and also adds logging in the zip error handler.

### CODE REVIEW

**Comment by peteonrails** [comment]
:+1: 

Running on linux building for Android using Ember CLI, was getting the "Can't set headers after sending" error. 

I can confirm that symlinks were causing the issue for me and that this change fixes it.

**Comment by mwbrooks** [comment]
Thanks for the nudge @peteonrails! I'll review and merge this pull request if there are no issues!

**Comment by mwbrooks** [comment]
@sundbry thanks for the pull request and sorry for the slow response. I've just looking into applying your work now.

I've setup my test directory as follows:
```
my-app/
|__ img/
|__ www/
     |__ img/ -> ../img
```

Your patch resolves the error that causes the process to terminate. Unfortunately, it's not adding `www/img/` to the zip archive.

I'll continue to look into it, but I'm dropping you this line in case I'm missing something obvious.

**Comment by mwbrooks** [comment]
I've merged #116 to resolve the sym-link issue on both Windows and OS X.
- `connect-phonegap@0.19.0`
- `phonegap@5.4.0`

Thanks for the PR @sundbry! Again, sorry for the delayed review.

**Comment by sundbry** [comment]
Cool thanks @mwbrooks, I'm glad to be able to contribute.

**Comment by darkyen** [comment]
is this not merged yet ?

**Comment by mwbrooks** [comment]
Hi @darkyen, I merged a different pull request, which has resolved the sym-link issue on OS X and Windows (from my own testing).

The fix is available in `phonegap@5.4.0`.

**Comment by darkyen** [comment]
@mwbrooks  damn, thanks for the reply and just installed phonegap@5.4.0 many thanks !

**Comment by mwbrooks** [comment]
Awesome!

**Pull request closed without merging**
