### PR TITLE
Fix zipping of apps with symlinks bug

### PR DESCRIPTION
**Pull request by eliotsykes**
Breaks phonegap projects created with `--link-to` option and any that
are using symlinks. `phonegap serve` cannot be used with projects
dependent on symlinks since v0.16.0 of connect-phonegap. v0.15.0 seems
to work well.

The work so far is investigating possible fixes.

### CODE REVIEW

**Comment by mwbrooks** [comment]
See #115 for more discussion around this issue.

@eliotsykes sorry, I didn't notice that you had a PR as well. Feel free to work off this PR to extend #115's work!

**Comment by eliotsykes** [comment]
Appear to have `zip.js` handling symlinks OK. Next up is to add test coverage in `zip.spec.js`, the beginnings of which can be seen in the PR so far.

**Comment by eliotsykes** [comment]
@mwbrooks spec added for this, feedback more than welcome on how to improve this PR

**Comment by eliotsykes** [comment]
[The Travis build failed](https://travis-ci.org/phonegap/connect-phonegap/builds/64708350) although the specs passed:

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```
Perhaps related to #113?

**Comment by mwbrooks** [comment]
@eliotsykes actually, I've noticed that the Travis-CI build has been failing regularly. It appears that all of the tests pass, but the test process does not exist. Eventually, Travis-CI times out and calls it a failure (rightfully so). I've seen this before, where one of the `http` server tests does not properly shutdown the server process. I imagine there was a commit that introduced this. Let me look into it!

**Comment by eliotsykes** [comment]
@mwbrooks running `npm test` locally also ran all the specs for me but the process didn't terminate, sounds like the same thing.

**Comment by mwbrooks** [comment]
@eliotsykes okay, I've closed off #113 and Travis-CI is green again. If you rebase your work, it should also be good!

**Comment by eliotsykes** [comment]
@mwbrooks fantastic, just rebased

**Comment by mwbrooks** [comment]
Yay! :+1:

**Comment by eliotsykes** [comment]
@mwbrooks The PR Travis build continued hanging as the test I added was removing all of the spies, including the #113 fixing gaze-related one. I've now modified zip.spec.js so each `it` block sets its current app. If there's any improvements to this, to make it more inline with the existing codebase, do let me know, I'm more than happy to make changes.

**Comment by eliotsykes** [comment]
@mwbrooks the PR Travis build continued to hang. I'd wiped out the good you did with #113 with a `removeAllSpies` call. That `removeAllSpies` call has now been removed and `zip.spec.js` has a new `setApp` function to set the current fixture app. I'm happy to make changes to this if there's improvements to be made to this PR to bring it inline with the project standards.

**Comment by eliotsykes** [comment]
@mwbrooks Is there anything needed further for this PR, I'm happy to clean it up.

**Comment by eliotsykes** [comment]
Workaround to downgrade phonegap to a version that uses an older version of connect-phonegap without this symlink/zip issue (connect-phonegap 0.15.0 is good, 0.16.0 and 0.16.1 have the issue):

Try uninstalling phonegap and reinstalling with the last version that used connect-phonegap 0.15.0, which appears to be phonegap 5.0.0-0.27.1 looking at this package.json:

https://github.com/phonegap/phonegap-cli/blob/5.0.0-0.27.1/package.json

```bash
# Uninstall global phonegap
npm uninstall -g phonegap

# Reinstall phonegap version that used connect-phonegap 0.15.0
npm install -g phonegap@5.0.0-0.27.1
```
```

**Comment by mwbrooks** [comment]
Hey @eliotsykes,

Sorry for the complete absence! Kicking off the New Year, I set aside time to review and merge your work. It's solid. I really wish I had taken the time to review it last year.

I've tested the sym-link resolution on OS X and Windows (as a shortcut) and it works well. Thanks as well for the great tests.

- I cherry-picked your pull request as commit 7538484.
- Publish on npm as `connect-phonegap@0.19.0`
- Available in `phonegap@5.4.0`

**Comment by eliotsykes** [comment]
Hey @mwbrooks - you're welcome and thank you for taking the time to review & merge this, and the kind words, best, E.

**Pull request closed without merging**
